databases:
  - name: student-portal-db
    databaseName: student_portal_db
    plan: free

services:
  - type: web
    name: student-portal
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn student_portal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_portal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        fromDatabase:
          name: student-portal-db
          property: connectionString
